### ISSUE TITLE
フィルター時の要素が見つからないエラー

### ISSUE THREAD

**Issue by ghost** [deepriver598/aws-billing#13]
E, [2016-07-11T07:53:48.686171 #5048] ERROR -- : no such element: Unable to locate element: {"method":"xpath","selector":"//span[text()='フィルター']"}
  (Session info: chrome=51.0.2704.106)
  (Driver info: chromedriver=2.22.397933 (1cab651507b88dec79b2b2a22d1943c01833cc1b),platform=Windows NT 6.1.7601 SP1 x86) (Selenium::WebDriver::Error::NoSuchElementError)
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:70:in `assert_ok'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/response.rb:34:in`initialize'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:78:in `new'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:78:in`create_response'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/default.rb:90:in `request'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:59:in`call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:627:in`execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:596:in `find_element_by'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/search_context.rb:61:in`find_element'
download-invoice.rb:110:in `filter_invoice'
download-invoice.rb:202:in`block in execute'
download-invoice.rb:165:in `each'
download-invoice.rb:165:in`execute'
download-invoice.rb:247:in `<main>'

**Comment by deepriver598** [comment]
実行環境に依存するものであったためクローズ。
