### ISSUE TITLE
サインイン後のタイムアウトエラー

### ISSUE THREAD

**Issue by ghost** [deepriver598/aws-billing#14]
E, [2016-07-11T07:59:30.636396 #5048] ERROR -- : Net::ReadTimeout (Net::ReadTimeout) C:/Ruby22/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill'
C:/Ruby22/lib/ruby/2.2.0/net/protocol.rb:152:in`rbuf_fill'
C:/Ruby22/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
C:/Ruby22/lib/ruby/2.2.0/net/protocol.rb:144:in`readline'
C:/Ruby22/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
C:/Ruby22/lib/ruby/2.2.0/net/http/response.rb:28:in`read_new'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1414:in `block in transport_request'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1411:in`catch'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1411:in `transport_request'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1384:in`request'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1377:in `block in request'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:853:in`start'
C:/Ruby22/lib/ruby/2.2.0/net/http.rb:1375:in `request'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/default.rb:107:in`response_for'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/http/common.rb:59:in`call'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:627:in`execute'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/remote/bridge.rb:596:in `find_element_by'
C:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.53.4/lib/selenium/webdriver/common/search_context.rb:61:in`find_element'
download-invoice.rb:70:in `password_expiration_screen?'
download-invoice.rb:185:in`block in execute'
download-invoice.rb:165:in `each'
download-invoice.rb:165:in`execute'
download-invoice.rb:247:in `<main>'

**Comment by deepriver598** [comment]
実行環境に依存するものであったためクローズ。
