### ISSUE TITLE
末日のinvoiceを取得できない（たぶんAWSの仕様）

### ISSUE THREAD

**Issue by ghost** [deepriver598/aws-billing#16]
AWSの請求書の画面で、月末日のinvoiceがフィルターで除外されてしまうようです。

　発行日が「2016年6月1日」から「2016年6月30日」のinvoiceをダウンロードしたい
　→「開始」欄に「2016年6月1日」、「終了」欄に「2016年6月30日」と指定すると
　　2016年6月30日発行のinvoiceが除外されてしまいます。

　※サポートのinvoiceが末日に発行であることが多いので、影響が大きいです。
　※開始日は除外されないようです。

終了日のフィルタを1日後ろにできれば良いかと思います。
（対象月以外のデータが入っても目検で除外できます）

**Comment by deepriver598** [comment]
9631c9eff450d70a6615f27b7f4065cdc8b57b3a
で対応完了
