### ISSUE TITLE
"session not created exception"で動作せず

### ISSUE THREAD

**Issue by ghost** [deepriver598/aws-billing#18]
問題は解決済みのため、情報連携みたいになりますが、

本日実行したところ、chromeの画面が開いた直後に消えてしまい、添付のログが出力されていました。
![0001](https://cloud.githubusercontent.com/assets/20395102/19991874/b280085e-a27c-11e6-8466-21d18119b67b.JPG)

chromeｄriverを最新のものに入れ替えたところ、正常に動作しました。

推測ですが、chromeが自動でバージョンアップされ、chromedriverの必要バージョンも上がったのかなあと
思っています。
以上です。

**Comment by deepriver598** [comment]
ご報告ありがとうございます。
解決されたとのことで良かったです。
また何かありましたらご連絡下さい。
