### ISSUE TITLE
ログレベルの修正

### ISSUE THREAD

**Issue by tetu1984** [deepriver598/aws-billing#3]
クレデンシャルが存在しない場合はその時点で処理を終了させるのでログレベルはエラーとしたい。
https://github.com/deepriver598/aws-billing/blob/7d8b6a365a8076922894201ef8082362473f4891/download-invoice/bin/download-invoice.rb#L138

処理対象のアカウントにはInvoiceが存在するはずなので、Invoiceが存在しない場合は警告としたい。
https://github.com/deepriver598/aws-billing/blob/7d8b6a365a8076922894201ef8082362473f4891/download-invoice/bin/download-invoice.rb#L177

**Comment by deepriver598** [comment]
対応済み

**Comment by tetu1984** [comment]
補足： https://github.com/deepriver598/aws-billing/pull/7 で対応
