### ISSUE TITLE
クレデンシャル情報格納ディレクトリチェックに不備がある

### ISSUE THREAD

**Issue by tetu1984** [deepriver598/aws-billing#5]
https://github.com/deepriver598/aws-billing/blob/7d8b6a365a8076922894201ef8082362473f4891/download-invoice/bin/download-invoice.rb#L135

> csv_files = read_files(@credential_pattern) unless Dir.exist?(@credential_pattern)

ディレクトリが存在したら、クレデンシャル情報があるはず、と考えるべきなので以下かな。
csv_files = read_files(@credential_pattern) if Dir.exist?(File.dirname(@credential_pattern))

**Comment by deepriver598** [comment]
対応済み

**Comment by tetu1984** [comment]
補足： https://github.com/deepriver598/aws-billing/pull/7 で対応
